name: build-and-push-cups

on:
    push:
      branches: [ "main" ]
      paths:
        - "Dockerfile"
        - ".github/workflows/cups.yml"
    schedule:
      - cron: "0 0 1 * *"   # mensal, 00:00 UTC no dia 1
    workflow_dispatch:  

env:
  IMAGE_NAME: cateim/cups
  # Ajuste a referência do CUPS se quiser fixar uma versão estável
  CUPS_REF: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Opcional, mas recomendado em runners x86 quando o alvo é ARM
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          build-args: |
            CUPS_REF=${{ env.CUPS_REF }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
